//
//  BaseInteractor.swift
//  VIP-sample
//
//  Created by Bahadır Enes Atay on 27.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BaseBusinessLogic {
    func getSeries(request: SeriesRequest)
}

class Interactor {
    var presenter: BasePresentationLogic?
 
}

extension Interactor: BaseBusinessLogic {
    func getSeries(request: SeriesRequest) {
        Worker().getSeries(request, onSuccess: { [weak self] series in
            self?.presenter?.presentSeries(response: SeriesList.FetchRequest.Response(series: series.search, keyword: request.series!))
        }, onError: { [weak self] error in
            self?.presenter?.presentError(error)
        })
    }
}
