//
//  BaseRouter.swift
//  VIP-sample
//
//  Created by Bahadır Enes Atay on 27.10.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol BaseRoutingLogic {
    func navigate(from source: BaseViewController, to destination: BaseViewController)
    func present(from source: BaseViewController, to destination: BaseViewController)
}

class Router: NSObject {
    weak var viewController: BaseViewController?
 
}

extension Router: BaseRoutingLogic {
    func navigate(from source: BaseViewController, to destination: BaseViewController) {
        source.navigationController?.pushViewController(destination, animated: true)
    }
    
    func present(from source: BaseViewController, to destination: BaseViewController) {
        source.navigationController?.present(destination, animated: true, completion: nil)
    }
}

